name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0

      - name: Run tests
        run: zig build test

      - name: Build debug
        run: zig build

      - name: Build release
        run: zig build -Doptimize=ReleaseFast

  build-cross-platform:
    name: Build Cross Platform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-linux
          - x86_64-windows
          - x86_64-macos
          - aarch64-macos

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0

      - name: Build for ${{ matrix.target }}
        run: zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.target }}
